export const routesLinks = {
  register: "/register",
  login: "/login",
  remoteCapture: "/remote-capture",
  notFound: "*",
  unauthorized: "/unauthorized",
  client: "/client",
  freelancer: "/freelancer",
  userProfile: "/user-profile",
  availableFreelancers: "/available-freelancers",
  availableClients: "/available-clients",
  myClients: "/my-clients",
  myFreelancers: "/my-freelancers",
  projects: "/projects",
  invoices: "/invoices",
  contracts: "/contracts",
  payments: "/payments",
  boards: "/boards",
  allProjects: "/all-projects",
  proposals: "/proposals",
  calendar: "/calendar",
};
